name        : randrproto
version     : 1.5.0
release     : 5
source     :
    - http://xorg.freedesktop.org/releases/individual/proto/randrproto-1.5.0.tar.gz : 8f8a716d6daa6ba05df97d513960d35a39e040600bf04b313633f11679006fab
license     :
    - MIT
summary     : X Resize and Rotate Extension (RandR)
component   : xorg.proto
patterns    : /
description : |
    This extension defines a protocol for clients to dynamically change X screens, so as to resize, rotate and reflect the root window of a screen.
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
